hydra:
  run:
    dir: ckpts/${model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

wandb_config:
  project: DiTAR
  wandb_run_name: bigvganvae_${now:%Y-%m-%d}_${now:%H-%M-%S}
  resume_id: null
  mode: online  # 'online' | 'offline' | 'disabled'

ckpts:
  logger: wandb
  log_samples: True
  save_per_updates: 2500
  keep_last_n_checkpoints: -1
  last_per_updates: 2500
  save_dir: ckpts/debug/${now:%Y-%m-%d}/${now:%H-%M-%S}
  checkpoint_step:

datasets:
  train_ds_path: data/Emilia_old/Emilia_ZH_EN_char
  val_ds_path: data/Emilia_old/LibriTTS_test-clean_char_1280

  batch_size_per_gpu: 400
  batch_size_type: frame
  max_samples: 16
  num_workers: 32
  target_sample_rate: 16000

optim:
  epochs: 10
  learning_rate: 1e-4
  num_warmup_updates: 10000
  grad_accumulation_steps: 1
  max_grad_norm: 1.0
  bnb_optimizer: False

model:
  name: DiTAR
  audio_type: vae_online
  audio_channels: 64        # BigVGAN-FlowVAE latent_dim; matches DEFAULT_BIGVGAN_VAE_CONFIG.
  patch_size: ${model.aggregation_encoder.patch_size}
  dim: ${model.backbone.hidden_size}
  mlp_hidden_dim: 512
  backbone:
    name: Qwen
    hidden_size: 1024
    version: qwen3
    qwen_config_path: checkpoints/Qwen3-0.6B/config.json
    pretrained_LM_path: checkpoints/Qwen3-0.6B
    load_pretrained_weights: true
  aggregation_encoder:
    name: qwen
    hidden_size: ${model.backbone.hidden_size}
    intermediate_size: 4096
    num_attention_heads: 16
    num_hidden_layers: 6
    patch_size: 4
    pool_type: cls
  loc_decoder:
    name: DiT
    model:
      dim: 1024
      out_dim: ${model.audio_channels}
      depth: 6
      heads: 16
      ff_mult: 4
      qk_norm: null
      pe_attn_head: null
      checkpoint_activations: False
    history_vae_window_size: 4
    drop_cond_prob: 0.1
  vocoder:
    mel_spec_type: semanticvae
    is_local: True  # use local offline ckpt or not
    local_path: checkpoints/Semantic-VAE/semantic_vae_1000k  # local vocoder path
    feature_extractor_ckpt: checkpoints/Semantic-VAE/semantic_vae_1000k

loss_weight:
  diff_loss: 1.0
  stop_loss: 1.0
